### ISSUE TITLE
ci: Proposal to add a linter and formatter

### ISSUE THREAD

**Issue by PedroChaparro** [hawks-atlanta/proxy-python#13]
Hi @MiguelMRojas, @andre154 :wave:.

Currently, your project doesn't have any code formatting or linting tools configured. What do you think about adding the following packages to your project:

- `black`: It's a Python code formatter, similar to `prettier` in JavaScript. There's even a [VsCode extension](https://marketplace.visualstudio.com/items?itemName=ms-python.black-formatter) available to automatically format files when you save changes.
- `Pylint`: It's a Python code linter, similar to `eslint` in JavaScript. It also offers a [VsCode extension](https://marketplace.visualstudio.com/items?itemName=ms-python.pylint). While I haven't personally used it, it can help detect issues like unused imports, variables, and more, as mentioned on [their website](https://www.pylint.org/).

Please note that this isn't mandatory, but it can assist in maintaining a consistent code style and catching errors early in the development process.

**Comment by MiguelMRojas** [comment]
I agree, I think they will help us to make the development process more orderly

**Comment by andre154** [comment]
Hi!
I think it's a great idea, I agree.
