### ISSUE TITLE
feat: Endpoint to update the password

### ISSUE THREAD

**Issue by PedroChaparro** [hawks-atlanta/proxy-python#20]

**Comment by andre154** [comment]
Hello! This service is not available yet, right?

**Comment by PedroChaparro** [comment]
> Hello! This service is not available yet, right?

You're right! It seems that they're working on it in [this branch](https://github.com/hawks-atlanta/gateway-java/tree/feat/update-password), but they haven't created a pull request yet

**Comment by andre154** [comment]
No problem, I just wanted to confirm, thanks :)

**Comment by PedroChaparro** [comment]
- [x] Ready in the SOAP service ([gateway-java/#68](https://github.com/hawks-atlanta/gateway-java/pull/68))
