### ISSUE TITLE
docs: Update openapi spec

### ISSUE THREAD

**Issue by PedroChaparro** [hawks-atlanta/proxy-python#35]
Remember that you should update your specification to align with the [.NET proxy](https://github.com/hawks-atlanta/proxy-net).

For instance, it appears that you're receiving the user token in the JSON body, while the .NET proxy is receiving it as a Bearer token.

**Comment by SantiagoGaonaC** [comment]
Hi, soon I will be sharing the openapi for the specification, for the openapi, there are some things in Spanish (only exceptions) while a standard is found for both.

**Comment by PedroChaparro** [comment]
> Hi, soon I will be sharing the openapi for the specification, for the openapi, there are some things in Spanish (only exceptions) while a standard is found for both.

Thanks. I've updated the `/auth/refresh` and `/auth/login` endpoints according to what I could see in the flutter client (#37).

**Comment by SantiagoGaonaC** [comment]
You can see the current new specification _proxy .NET_ [here](https://github.com/hawks-atlanta/gateway-java/blob/802907582b6b2722a783b5ab6e2ceb032414599e/docs/spec.openapi.yml)

**Comment by PedroChaparro** [comment]
It seems that you shared the gateway specification. It [this](https://github.com/hawks-atlanta/proxy-net/blob/feat/soap-implementation/Docs/openapi.json) your new specification?

**Comment by SantiagoGaonaC** [comment]
That's right!
